ImagePainting.Site.Web/Models/NavBarViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ImagePainting.Site.Web.Models
{
    public class NavBarViewModel
    {
        public bool IsAdmin { get; set; }

        public bool IsStaff { get; set; }

        public bool IsAdminOrEmployee { get; set; }

        public string UserFirstName { get; set; }
    }
}

ImagePainting.Site.Web/Controllers/HomeController.cs
using System.Web.Mvc;
using ImagePainting.Site.Web.Helpers;
using ImagePainting.Site.Web.Models;

namespace ImagePainting.Site.Web.Controllers
{
    public class HomeController : BaseController
    {
        private readonly IUserHelper _userHelper;
        private readonly IViewHelper _viewHelper;

        public HomeController(IViewHelper viewHelper, 
            IUserHelper userHelper) :base(viewHelper, userHelper)
        {
            _userHelper = userHelper;
            _viewHelper = viewHelper;
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult NavBar()
        {
            var model = GetNavViewModel();
            return PartialView(model);
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Index()
        {
            return View2(_userHelper);
        }

        private NavBarViewModel GetNavViewModel()
        {
            return new NavBarViewModel
            {
                IsAdmin = _userHelper.IsUserAdmin(),
                IsStaff = _userHelper.IsStaff(),
                IsAdminOrEmployee = _userHelper.IsAdminOrEmployee(),
                UserFirstName = _viewHelper.GetUserFirstName()
            };
        }
    }
}

ImagePainting.Site.Web/Controllers/ReportsController.cs
using ImagePainting.Site.Common.Interfaces.Repository;
using ImagePainting.Site.Common.Models.Reports;
using ImagePainting.Site.Web.Helpers;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace ImagePainting.Site.Web.Controllers
{
    [Authorize(Roles = RolesConstant.Admin)]
    public class ReportsController : BaseController
    {
        private readonly IReportRepository _reportRepository;

        public ReportsController(
            IReportRepository reportRepository,
            IViewHelper viewHelper,
            IUserHelper userHelper)
            : base(viewHelper, userHelper)
        {
            _reportRepository = reportRepository;
        }

        public ActionResult PurchaseOrder()
        {
            var model = new List<PurchaseOrderReportItem>();

            return View2("Purchases", model);
        }
        
        public async Task<ActionResult> PurchaseOrderList(PurchaseReportQuery query)
        {
            var report = await _reportRepository.GetPurchaseReport(query);

            return PartialView("_PurchaseOrdersTable", report);
        }

        public ActionResult Tasks()
        {
            var model = new TasksReport();

            return View2(model);
        }

        public async Task<PartialViewResult> TasksReport(TasksReportQuery query)
        {
            var report = await _reportRepository.GetTasksReport(query);

            return PartialView("_TasksTable", report);
        }

        public ActionResult ProjectedRevenue()
        {
            var model = new ProjectedRevenueReport();

            return View2(model);
        }
        
        public async Task<PartialViewResult> ProjectedRevenueList(ProjectedRevenueReportQuery query)
        {
            var model = await _reportRepository.GetProjectedRevenueReport(query);

            return PartialView("_ProjectedRevenueTableList", model);
        }

        public ActionResult ProjectedLabor(ProjectedLaborReportQuery query)
        {
            var model = new ProjectedLaborReport();

            return View2(model);
        }

        public async Task<PartialViewResult> ProjectedLaborList(ProjectedLaborReportQuery query)
        {
            var report = await _reportRepository.GetProjectedLaborReport(query);

            return PartialView("_ProjectedLaborTableList", report);
        }
    }
}

ImagePainting.Site.Web/Controllers/TasksController.cs
using ImagePainting.Site.Common.Helpers;
using ImagePainting.Site.Common.Interfaces;
using ImagePainting.Site.Common.Interfaces.Repository;
using ImagePainting.Site.Common.Interfaces.Service;
using ImagePainting.Site.Common.Models;
using ImagePainting.Site.Common.Models.Enums;
using ImagePainting.Site.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using ImagePainting.Site.Web.Helpers;
using static ImagePainting.Site.Common.Helpers.DateHelper;
using static ImagePainting.Site.Web.Helpers.RolesConstant;

namespace ImagePainting.Site.Web.Controllers
{
    [Authorize]
    public class TasksController : BaseController
    {
        private readonly ITaskComposerService _taskService;
        private readonly IWorkOrderTaskManager _taskManager;
        private readonly ILogger _logger;
        private readonly IPurchaseOrderRepository _purchaseOrderRepository;
        private readonly IUserCacheService _userCacheService;
        private readonly IViewHelper _viewHelper;
        private readonly IUserHelper _userHelper;

        public TasksController(
            ITaskComposerService taskService,
            IWorkOrderTaskManager taskManager,
            ILogger logger,
            IUserCacheService userCacheService,
            IPurchaseOrderRepository purchaseOrderRepository,
            IViewHelper viewHelper, IUserHelper userHelper) : base(viewHelper, userHelper)

        {
            _taskService = taskService;
            _taskManager = taskManager;
            _logger = logger;
            _purchaseOrderRepository = purchaseOrderRepository;
            _userCacheService = userCacheService;
            _viewHelper = viewHelper;
            _userHelper = userHelper;
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            var tasks = await _taskService.GetTaskSchemas();
            return View(tasks);
        }

        [HttpGet, Authorize(Roles = Staff)]
        public async Task<ActionResult> Task(int id = 0)
        {
            var task = await _taskService.GetWorkSchemaTask(id);
            return View2(task);
        }

        [HttpGet, Authorize(Roles = Staff)]
        public async Task<ActionResult> ViewTask(int id)
        {
            var task = await _taskManager.GetTaskWithPermissions(id, true);

            if (!task.IsMainTask)
            {
                var mainTask = await _taskManager.GetMainTask(id);
                ViewBag.MainTaskId = mainTask.Id;
            }
            else
            {
                ViewBag.MainTaskId = task.Id;
            }

            return View2(task);
        }

        [HttpPost, Authorize(Roles = Staff)]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SaveWorkOrderTask(WorkOrderTask task)
        {
            var result = await _taskManager.SaveWorkOrderTask(task);

            if (Request.IsAjaxRequest())
            {
                result.RemovePermission();
                return Json(result);
            }

            return RedirectToAction("UpcomingTasks");
        }

        [HttpPost, Authorize(Roles = Staff)]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> UpdateTaskSchedule(TaskSchedule task)
        {
            var result = await _taskManager.UpdateTaskSchedule(task);
            result.RemovePermission();
            return Json(result);
        }

        [HttpPost, Authorize(Roles = Staff)]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Task(WorkOrderTaskSchema task)
        {
            if (!ModelState.IsValid)
            {
                return View2(task);
            }

            await _taskService.SaveTaskSchema(task);
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = Staff)]
        public Task<ActionResult> UpcomingTasks(int pageNumber = 0)
        {
            var today = GetLocalDateToday();
            var searchCriteria = new TaskSearchCriteria
            {
                IsUpcoming = true,
                IncludeCrew = true,
                IncludeWorkOrder = true,
                OrderByAscending = true,
                PageNumber = pageNumber,
                DateRange = new DateTimeRange
                {
                    BeginDateTime = today,
                    EndDateTime = today.AddDays(30)
                }
            };

            ViewBag.minDate = today;

            return CalendarView(searchCriteria, true);
        }

        [HttpGet]
        [Authorize(Roles = Staff)]
        public Task<ActionResult> CompletedTasks(int pageNumber = 0)
        {
            var today = GetLocalDateToday();
            var searchCriteria = new TaskSearchCriteria
            {
                IsCompleted = true,
                IncludeCrew = true,
                IncludeWorkOrder = true,
                OrderByAscending = false,
                PageNumber = pageNumber,
                DateRange = new DateTimeRange
                {
                    BeginDateTime = today.AddDays(-30),
                    EndDateTime = today
                }
            };

            return CalendarView(searchCriteria, true);
        }

        [HttpGet]
        [Authorize(Roles = Staff)]
        public Task<ActionResult> OverdueTasks(int pageNumber = 0)
        {
            var today = GetLocalDateToday();
            var searchCriteria = new TaskSearchCriteria
            {
                IsOverdued = true,
                IncludeCrew = true,
                IncludeWorkOrder = true,
                OrderByAscending = false,
                PageNumber = pageNumber,
                DateRange = new DateTimeRange
                {
                    BeginDateTime = today.AddDays(-30),
                    EndDateTime = today
                }
            };

            ViewBag.maxDate = today;

            return CalendarView(searchCriteria, true);
        }

        [HttpGet]
        [Authorize(Roles = Staff)]
        public Task<ActionResult> AllTasks(int pageNumber = 0)
        {
            var today = GetLocalDateToday();
            var searchCriteria = new TaskSearchCriteria
            {
                IncludeCrew = true,
                IncludeWorkOrder = true,
                OrderByAscending = true,
                PageNumber = pageNumber,
                DateRange = new DateTimeRange
                {
                    BeginDateTime = today.AddDays(-30),
                    EndDateTime = today
                }
            };

            return CalendarView(searchCriteria, true);
        }

        [HttpPost]
        [Authorize(Roles = Staff)]
        public async Task<ActionResult> LoadTasks(TaskSearchCriteria criteria)
        {
            var dateRange = criteria.ToDateRange();

            if (!criteria.CrewIds.IsNullOrEmpty())
            {
                criteria.CrewIds = CleanUpCrewIds(criteria.CrewIds.ToArray());
            }

            ViewBag.PageNumber = criteria.PageNumber;
            ViewBag.DateTimeRange = dateRange;

            criteria.IncludeCrew = true;
            criteria.IncludeCommunity = true;

            var viewModel = await GetCalendarViewModel2(criteria, dateRange);
            
            SetNavButtonsDisplay(criteria, dateRange);

            return PartialView("WorkOrderTasks", viewModel);
        }

        [HttpPost, Authorize(Roles = Staff)]
        public async Task<ActionResult> CompleteTask(WorkOrderTask task)
        {
            var result = await _taskManager.CompleteTask(task);

            result.RemovePermission();

            return Json(result);
        }

        [HttpPost, Authorize(Roles = Admin)]
        public async Task<ActionResult> UnlockTask(long id)
        {
            var result = await _taskManager.UnlockTask(id);

            result.RemovePermission();

            return Json(result);
        }

        [HttpPost, Authorize(Roles = Admin)]
        public async Task<ActionResult> DeferTask(long id)
        {
            await _taskService.SetTaskDeferState(id);

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        [HttpPost, Authorize(Roles = Admin)]
        public async Task EmailScheduleTask(IEnumerable<long> ids, string note, FreeCrewViewModel freeCrewsModel)
        {
            if (!freeCrewsModel.FreeCrewIds.IsNullOrEmpty())
            {
                await _taskService.SendNoTaskEmailAsync(freeCrewsModel.FreeCrewIds, freeCrewsModel.TaskDate, freeCrewsModel.Note);
            }

            if (!ids.IsNullOrEmpty())
            {
                await _taskService.SendWorkOrderMails(ids, note);
            }
        }

        [HttpPost, Authorize(Roles = Admin)]
        public async Task<ActionResult> DeleteTaskSchema(int id)
        {
            try
            {
                await _taskService.DeleteTaskSchema(id);
            }
            catch (Exception ex)
            {
                _logger.Error(ex);

                var msg = "Deleting task schema failed!";

                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, msg);
            }

            return Json(new { Success = true });
        }

        [HttpPost, Authorize(Roles = Admin)]
        public async Task<JsonResult> UpdateUnassignedCrewStatus(string crewId, DateTime scheduledDate, bool status)
        {
            await _taskService.UpdateUnAssignedCrewSetting(new List<string>{crewId}, scheduledDate, busy: status);

            return Json(new {Success = true});
        }

        [HttpGet]
        public async Task<JsonResult> GetBusyUser(string crewId, DateTime date)
        {
            var user = await _taskService.GetBusyUser(crewId, date);

            return Json(user, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public async Task<JsonResult> GetTaskPdfTemplate(long taskId)
        {

ImagePainting.Site.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<div class="jumbotron child">
    <h1>About Image Painting of Florida Inc.</h1>
</div>

<section class="container body-content text-center">
    <h3>
        Image Painting of Florida Inc. has the finest painters in the industry with decades of experiece. We work with the nation's largest builders like Beazer Homes, M/I Homes, David Weekly etc.
        Please, reach out to us for any of your painting jobs.
    </h3>
</section>

ImagePainting.Site.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<section class="container body-content">
    <h2>@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</section>

ImagePainting.Site.Web/Views/Home/Index.cshtml
@using Microsoft.AspNet.Identity
@using ImagePainting.Site.Common.Models.Enums
@model SiteViewModel<IUserHelper>

@{
    ViewBag.Title = "Home";
    var isStaff = Model.UserHelper.IsStaff();
}

<div class="jumbotron">
    <h1>Image Painting of Florida Inc.</h1>
    @Html.ActionLink("Learn More", "About", "Home", null, new { @class = "primary-button" })
</div>

<section class="container home">
    <div class="row">
        <div class="col-md-4">
            <img src="~/Images/intelligence.svg" title="Work Orders" />
            <h2>Work Orders</h2>
            <ul>
                <li><a href="@Url.Action("Index", "WorkOrders")">Existing Work Orders</a></li>
                <li><a href="@Url.Action("WorkOrder", "WorkOrders")">Create New Work Orders</a></li>
                <li><a href="@Url.Action("Index", "WorkOrders")">Process Work Orders</a></li>
            </ul>
        </div>
        @if (isStaff)
        {
            <div class="col-md-4">
                <img src="~/Images/development.svg" title="Calendar" />
                <h2>Tasks</h2>
                <ul>
                    <li><a href="@Url.Action("UpcomingTasks", "Tasks")">View Upcoming Tasks</a></li>
                    <li><a href="@Url.Action("CompletedTasks","Tasks")">View Completed Tasks</a></li>
                    <li><a href="@Url.Action("OverdueTasks", "Tasks")">View Overdue Tasks</a></li>
                </ul>
            </div>
        }
        <div class="col-md-4">
            <img src="~/Images/solutions.svg" title="About Us" />
            <h2>About Us</h2>
            <ul>
                <li><a href="@Url.Action("About", "Home")">Learn More About Us</a></li>
                <li><a href="@Url.Action("Builders","Communities")">See Our Builders</a></li>
                <li><a href="@Url.Action("Index","Communities")">See Our Communities</a></li>
            </ul>
        </div>
    </div>
</section>

ImagePainting.Site.Web/Views/Home/NavBar.cshtml
@model NavBarViewModel
    

<nav class="navbar">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">
                <img src="~/Images/site-logo.jpg" />
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <div class="nav-holder">
                <a class="phone" title="Call Us: 813-388-3157" href="tel:8133883157">Call Us: 813-388-3157</a>
                @Html.Partial("_LoginPartial", new ViewDataDictionary { { "FirstName", Model.UserFirstName } })
                <ul class="nav navbar-nav nav-bar-left">
                    @if (Model.IsAdmin)
                    {
                        <li class="dropdown @ViewBag.DashboardActive">@Html.ActionLink("Dashboard", "Index", "Dashboard")</li>
                    }
                    @if (Model.IsAdminOrEmployee)
                    {
                        <li class="dropdown @ViewBag.CommunitiesActive">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown">Builders</a>
                            <ul class="dropdown-menu dropdown-menu-left animated-2x animated fadeIn">

                                <li>@Html.ActionLink("Builders", "Builders", "Communities")</li>

                                <li>@Html.ActionLink("Communities", "Index", "Communities")</li>
                                <li>@Html.ActionLink("Plans", "Plans", "Communities")</li>
                                <li>@Html.ActionLink("Interior Color Schemes", "InteriorColorSchemes", "Communities")</li>
                                <li>@Html.ActionLink("Exterior Color Schemes", "ExteriorColorSchemes", "Communities")</li>
                            </ul>
                        </li>
                    }
                    @if (Model.IsStaff)
                    {
                        <li class="dropdown @ViewBag.WorkOrdersActive">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown">Work Orders</a>
                            <ul class="dropdown-menu dropdown-menu-left animated-2x animated fadeIn">
                                @if (Model.IsAdmin)
                                {
                                    <li>@Html.ActionLink("Work Orders", "Index", "WorkOrders")</li>
                                }
                                <li>@Html.ActionLink("Upcoming Tasks", "UpcomingTasks", "Tasks")</li>
                                <li>@Html.ActionLink("Completed Tasks", "CompletedTasks", "Tasks")</li>
                                <li>@Html.ActionLink("Overdue Tasks", "OverdueTasks", "Tasks")</li>
                                <li>@Html.ActionLink("All Tasks", "AllTasks", "Tasks")</li>
                            </ul>
                        </li>
                    }
                    @if (Model.IsAdmin)
                    {
                        <li class="dropdown @ViewBag.SetupActive">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown">Setup</a>
                            <ul class="dropdown-menu dropdown-menu-left animated-2x animated fadeIn">
                                @if (Model.IsAdmin)
                                {
                                    <li>@Html.ActionLink("Tasks", "Index", "Tasks")</li>
                                        <li>@Html.ActionLink("Labor Costs", "LaborCosts", "Communities")</li>
                                }
                                <li>@Html.ActionLink("Paint Stores", "Index", "PaintStores")</li>
                            </ul>
                        </li>
                    }
                    @if (Model.IsAdmin)
                    {
                        <li class="dropdown @ViewBag.ReportActive">
                            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown">Reports</a>
                            <ul class="dropdown-menu dropdown-menu-left animated-2x animated fadeIn">
                                <li>@Html.ActionLink("Tasks Report", "Tasks", "Reports")</li>
                                <li>@Html.ActionLink("Revenue Projection Report", "ProjectedRevenue", "Reports")</li>
                                <li>@Html.ActionLink("Labor Projection Report", "ProjectedLabor", "Reports")</li>
                                <li>@Html.ActionLink("Purchase Order Report", "PurchaseOrder", "Reports")</li>
                            </ul>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
</nav>