ImagePainting.Site.Web/Controllers/CommunitiesController.cs
using ImagePainting.Site.Domain.Models;
using ImagePainting.Site.Web.Helpers;
using System;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Linq;
using System.Collections.Generic;
using ImagePainting.Site.Common.Models;
using ImagePainting.Site.Common.Interfaces.Service;
using static ImagePainting.Site.Web.Helpers.RolesConstant;

namespace ImagePainting.Site.Web.Controllers
{
    [Authorize(Roles = AdminAndEmployee)]
    public class CommunitiesController : BaseController
    {
        private ICommunityComposerService _composerService;
        private ILogger _logger;

        public CommunitiesController(
            ICommunityComposerService composerService, 
            ILogger logger,
            IViewHelper viewHelper, 
            IUserHelper userHelper)
            :base(viewHelper, userHelper)
        {
            _composerService = composerService;
            _logger = logger;
        }

        public async Task<ActionResult> Index()
        {
            var communities = await _composerService.GetCommunities();

            return View2(communities.ToList());
        }

        #region Communities
        [HttpGet]
        public async Task<ActionResult> Community(int id = 0)
        {
            try
            {
                var community = await _composerService.GetCommunity(id);

                var communityViewModel = new CommunityViewModel();

                communityViewModel.MapToViewModel(community);

                return View2(communityViewModel);
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View();
            }
        }

        [HttpPost]
        [Authorize(Roles = Admin)]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Community(CommunityViewModel communityViewModel)
        {            
            if (!ModelState.IsValid)
            {
                return View2(communityViewModel);
            }

            communityViewModel.Builders = await _composerService.GetBuilders(communityViewModel.BuilderIds);

            var community = communityViewModel.MapFromViewModel();

            var newCommunity = await _composerService.SaveCommunity(community);

            if (Request.IsAjaxRequest())
            {
                newCommunity.CommunitySummary();

                return Json(newCommunity);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize(Roles = Admin)]
        public async Task<ActionResult> DeleteCommunity(int id)
        {
            try
            {
                var deletedCommunity = await _composerService.DeleteCommunity(id);

                if (!deletedCommunity)
                {
                    var msg = "Unable to delete this community!";

                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, msg);
                }
            }
            catch (Exception ex)
            {
                _logger.Error(ex);

                var msg = "Unable to delete this community";

                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, msg);
            }

            return Json(new { Success = true });
        }
        #endregion

        #region Builders
        [HttpGet]
        public async Task<ActionResult> Builders()
        {
            var builders = await _composerService.GetBuilders();
           
            return View2(builders);
        }

        [HttpGet]
        public async Task<ActionResult> Builder(int id = 0)
        {
            var builder = await _composerService.GetBuilder(id, includePlans: true);

            return View2(builder);
        }

        [HttpGet]
        public async Task<JsonResult> BuilderCommunities(int id)
        {
            var builderCommunities =  await _composerService.GetCommunitiesSummary(id);

            return Json(builderCommunities, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [Authorize(Roles = Admin)]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Builder(Builder builder, int builderCopiedCostId = 0)
        {
            if (!ModelState.IsValid)
            {
                return View2(builder);
            }

            var newBuilder = await _composerService.SaveBuilder(builder, builderCopiedCostId);

            if (Request.IsAjaxRequest())
            {
                newBuilder.BuilderSummary();
                return Json(newBuilder);
            }

            return RedirectToAction("Builders");
        }

        [HttpPost]
        [Authorize(Roles = Admin)]
        public async Task<ActionResult> DeleteBuilder(int id)
        {
            var deletedBuilder = await _composerService.DeleteBuilder(id);

            if (!deletedBuilder)
            {
                var msg = "Cannot delete this builder as it is currently associated with community, but you can make it inactive";

                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, msg);
            }

            return Json(new { Success = true });
        }
        #endregion

        #region Costs
        [HttpGet]
        [Authorize(Roles = Admin)]
        public async Task<ActionResult> Costs(int id)
        {
            var builderCosts = await _composerService.GetBuilder(id, true)
                .ContinueWith(x =>
                {
                    x.Result.Costs = x.Result.Costs.OrderBy(y => y.CostItem.Order).ToList();
                    return x.Result;
                });

            return View2(builderCosts);
        }

        [HttpGet]
        public async Task<ActionResult> LaborCosts()
        {
            var costItems = await _composerService.GetCostItems()
                .ContinueWith(x => x.Result.OrderBy(y => y.Order));

            return View2(costItems.ToList());
        }

        [HttpPost]
        [Authorize(Roles = Admin)]
        public async Task<ActionResult> LaborCosts(IEnumerable<CostItem> costItems)
        {
            await _composerService.UpdateCostItems(costItems, true);

            return RedirectToAction("LaborCosts");
        }

        [HttpPost]
        [Authorize(Roles = Admin)]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Costs(int id, Builder builder)
        {
            if (id == default(int))
            {
                var costItems = builder.Costs.Select(x => x.CostItem);

                await _composerService.UpdateCostItems(costItems);
            }
            else
            {
                builder.Id = id;
                await _composerService.UpdateBuilderCosts(builder);
            }

            return RedirectToAction("Builders");
        }

        [HttpGet]
        public async Task<ActionResult> Cost(int id = 0, int costId = 0)
        {
            var cost = await _composerService.GetCostForBuilder(id, costId);

            return View2(cost);
        }

        [HttpPost]
        [Authorize(Roles = Admin)]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Cost(Cost cost)
        {
            if (cost.BuilderId == default(int))
            {
                await _composerService.SaveCostItem(cost.CostItem);
            }
            else
            {
                await _composerService.SaveCost(cost);
            }

            return RedirectToAction("Costs", new { id = cost.BuilderId });
        }

        [HttpPost]
        [Authorize(Roles = Admin)]
        public async Task<ActionResult> DeleteCost(int id, int builderId)
        {
            try
            {
                await _composerService.DeleteCost(id);
            }
            catch(Exception ex)
            {
                _logger.Equals(ex);

                var msg = "Unable to delete cost!";

                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, msg);
            }

            return RedirectToAction("Costs", new { id = builderId });
        }

        [HttpPost]
        [Authorize(Roles = Admin)]
        public async Task<ActionResult> DeleteCostItem(int id)
        {
            try
            {
                await _composerService.DeleteCostItem(id);
            }
            catch (Exception ex)
            {
                _logger.Equals(ex);

                var msg = "Unable to delete cost!";

                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, msg);
            }

            return Json(new { Success = true });
        }
#endregion

        #region Plans

        [HttpGet]
        public async Task<ActionResult> Plans()
        {
            var allPlans = await _composerService.GetPlans();
            return View2(allPlans.ToList());
        }

        [HttpGet]
        public async Task<ActionResult> Plan(int id = 0, int builderId = 0)
        {
            var plan = await _composerService.GetPlan(id, includeElevations: true, includeCommunities:true);

            if (plan.Id == 0)
            {
                plan.BuilderId = builderId;
            }

            return View2(plan);
        }

        [HttpPost]
        [Authorize(Roles = Admin)]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Plan(Plan plan)
        {
            if (!ModelState.IsValid)
            {
                return View2(plan);
            }

            var newPlan = await _composerService.SavePlan(plan);

            if (Request.IsAjaxRequest())
            {
                return Json(newPlan);
            }

            return RedirectToAction("Plans");
        }

        [HttpPost]
        [Authorize(Roles = Admin)]
        public async Task<ActionResult> DeletePlan(int id)
        {
            var deletedPlan = await _composerService.DeletePlan(id);

            if (!deletedPlan)
            {

ImagePainting.Site.Web/Views/Communities/Builders.cshtml
@model SiteViewModel<List<Builder>>

@{
    ViewBag.Title = "Builders";
    ViewBag.CommunitiesActive = "active";

    var isAdmin = Model.UserHelper.IsUserAdmin();
    var model = Model.ViewModel;
}

<div class="jumbotron child">
    <h1>Builders</h1>
</div>

<section class="container body-content">
    @if (isAdmin)
    {
    <div class="row add-container">
        <div class="col-md-12">
            @Html.ActionLink("Add", "Builder", null, new { @class = "btn btn-primary pull-right" })

        </div>
    </div>
    }

    <table class="table data-table">
        <thead>
            <tr>
                <th>Active</th>
                <th>Name</th>
                <th>Address</th>
                @if (isAdmin)
                {
                    <th>Supplies</th>
                    <th></th>
                }
            </tr>
        </thead>
        <tbody>
            @foreach (var builder in model)
            {
                <tr>
                    <td>@(builder.Active ? "Yes" : "No")</td>
                    <td>@Html.ActionLink(builder.Name, "builder", new { id = builder.Id }, new { @title = "click to edit" })</td>
                    <td>@builder.Address, @builder.City @builder.State</td>

                    @if (isAdmin)
                    {
                        <td>@Html.ActionLink("Supplies", "Supplies", "Communities", new { builderId = builder.Id }, null)</td>
                        <td>@Html.ActionLink("Pricing", "Costs", new { id = builder.Id })</td>
                    }
                </tr>
            }
        </tbody>
    </table>
</section>

ImagePainting.Site.Web/Views/Communities/Community.cshtml
@model SiteViewModel<ImagePainting.Site.Domain.Models.CommunityViewModel>

@{
    ViewBag.Title = "Community";
    ViewBag.CommunitiesActive = "active";
    var isAdmin = Model.UserHelper.IsUserAdmin();
    var model = Model.ViewModel;
}

@if (!ViewBag.IsPartial)
{
    <div class="jumbotron child">
        <h1>@(string.IsNullOrEmpty(model.Name) ? "New Community" : $"Community - {model.Name}")</h1>
    </div>
}

<section class="container body-content">
    @if (ViewBag.IsPartial)
    {
        <h2>@(string.IsNullOrEmpty(model.Name) ? "New Community" : $"Community - {model.Name}")</h2>
    }

    @using (Html.BeginForm("Community", "Communities", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @(Html.For(model).HiddenFor(x => x.Id))

        <div class="checkbox">
            <label class="check">
                @(Html.For(model).CheckBoxFor(x => x.Active,ViewHelper.GetHtmlAttributes(disabled: !isAdmin, formControl: false))) Active
                <span class="animated-checkbox"><i class="animated-checkbox-icon glyphicon glyphicon-ok"></i></span>
            </label>
        </div>
        <div class="row">
            <div class="form-group col-md-6">
                <label for="Name">Community Name</label>
                @(Html.For(model).TextBoxFor(x => x.Name,ViewHelper.GetHtmlAttributes(maxLength: 64, disabled: !isAdmin)))
                @(Html.For(model).ValidationMessageFor(x => x.Name, "", new { @class = "text-danger" }))
            </div>

            <div class="form-group col-md-6">
                <label class="required-field" for="Name">Abbreviation</label>
                @(Html.For(model).TextBoxFor(x => x.Abbreviation,ViewHelper.GetHtmlAttributes(maxLength: 3, disabled: !isAdmin)))
                @(Html.For(model).ValidationMessageFor(x => x.Abbreviation, "", new { @class = "text-danger" }))
            </div>
        </div>

        <div class="form-group">
            <label class="required-field" for="Name">Builder</label>

            @(Html.For(model).ListBoxFor(x => x.BuilderIds, Model.ViewHelper.GetBuilderOptions(model.Builders.Select(x => x.Id).ToList()),ViewHelper.GetHtmlAttributes(multiple: true, disabled: !isAdmin)))
            @(Html.For(model).ValidationMessageFor(x => x.BuilderIds, null, new { @class = "text-danger" }))
        </div>
        <div class="form-group">
            <label for="Notes">Notes</label>
            @(Html.For(model).TextAreaFor(x => x.Notes,ViewHelper.GetHtmlAttributes(disabled: !isAdmin, rows: 4)))
        </div>

        <div class="form-group">
            @PageHelpers.CancelButton("Index", "Communities")
            @if (model.Id > 0 && isAdmin)
            {
                <button class="btn btn-danger"
                        data-execute="true"
                        data-url="@Url.Action("DeleteCommunity", "Communities")"
                        data-data="@((new {id = model.Id}).ToJson())"
                        data-confirmmessage='Do you want to delete "@Model.ViewModel.Name" and all the associated plans?'
                        data-confirmtitle="Delete Community?"
                        data-redirect="@Url.Action("Index", "Communities")">
                    Delete
                </button>
            }

            @if (isAdmin)
            {
                <input type="submit" value="Save" class="btn btn-primary" />
            }
        </div>
    }

    @if (model.Id > 0 && isAdmin)
    {
        Html.RenderAction("Files", "FileUploads", new { ownerId = model.Id, ownerType = FileOwnerType.Community });
    }
</section>

ImagePainting.Site.Web/Views/Communities/Costs.cshtml
@model SiteViewModel<ImagePainting.Site.Common.Models.Builder>

@{
    ViewBag.Title = "Pricing";
    var model = Model.ViewModel;

    if (model.Id == default(int))
    {
        ViewBag.SetupActive = "active";
    }
    else
    {
        ViewBag.CommunitiesActive = "active";
    };

    var isAdmin = Model.UserHelper.IsUserAdmin();
}

<div class="jumbotron child">
    <h1>@($"Pricing - {model.Name}")</h1>
</div>

<section class="container body-content">
    <div class="row">
        @if (model.Id != default(int) && isAdmin)
        {
            @Html.ActionLink("New Cost", "Cost", new { id = model.Id }, new { @class = "btn btn-primary pull-right" })
        }
    </div>
    @using (Html.BeginForm("Costs", "Communities", FormMethod.Post, new { novalidate = true }))
    {
        @Html.AntiForgeryToken()

        @(Html.For(model).HiddenFor(x => x.Id))

        <div class="row">
            @for (var i = 0; i < model.Costs.Count(); i++)
            {
                var cost = model.Costs.ElementAt(i);
                <div class="col-md-3 form-group">
                    @Html.Hidden($"Builder.Costs[{i}].BuilderId", model.Id)
                    @Html.Hidden($"Builder.Costs[{i}].Id", @cost.Id)
                    @Html.Hidden($"Builder.Costs[{i}].CostItemId", @cost.CostItemId)
                    @(cost.CostItem.Name == SiteContants.BASE_PRICE ? Html.Label(cost.CostItem.Name, new { @class = "base-price no-margin" }) : Html.ActionLink(cost.CostItem.Name, "Cost", new { id = model.Id, costId = cost.Id}))
                    <div class="input-group">
                        <div class="input-group-addon">$</div>
                        @Html.TextBox($"Builder.Costs[{i}].Amount", @cost.Amount, ViewHelper.GetHtmlAttributes(type:"number", disabled:!isAdmin))
                    </div>
                </div>
            }
        </div>

        <div class="form-group">
            @Html.ActionLink("Cancel", "Builders", null, new { @class = "btn btn-default", id = "btn-cancel" })


            @if (isAdmin)
            {
                <input type="submit" value="Save" class="btn btn-primary" />
            }
        </div>
    }
</section>

ImagePainting.Site.Web/Views/Communities/ExteriorColorScheme.cshtml
@model SiteViewModel<ImagePainting.Site.Common.Models.ExteriorColorScheme>

@{
    var model = Model.ViewModel;
    ViewBag.Title = "Exterior Color Scheme";
    ViewBag.CommunitiesActive = "active";
    var isAdmin = Model.UserHelper.IsUserAdmin();
}

@if (!ViewBag.IsPartial)
{
    <div class="jumbotron child">
        <h1>@(Model.ViewModel.Id == 0 ? "New Exterior Color Scheme" : $"Exterior Color Scheme - {model.ExteriorBase}")</h1>
    </div>
}

<section class="container body-content">
    @if (ViewBag.IsPartial)
    {
        <div class="form-group">
            <h2>@(Model.ViewModel.Id == 0 ? "New Exterior Color Scheme" : $"Exterior Color Scheme - {model.ExteriorBase}")</h2>
        </div>
    }

    @using (Html.BeginForm("ExteriorColorScheme", "Communities", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        @(Html.For(model).HiddenFor(x => x.Id))

            <div class="row">

                <div class="form-group col-md-12">
                    <label for="colorcode" class="required-field">Color code</label>
                    @(Html.For(model).TextBoxFor(x => x.ColorCode,ViewHelper.GetHtmlAttributes(disabled: !isAdmin)))
                    @(Html.For(model).ValidationMessageFor(x => x.ColorCode, null, new { @class = "text-danger" }))
                </div>
            </div>
           
            <div class="row">
                <div class="form-group col-md-4">
                    <label for="exteriorbody" class="required-field">Exterior Base</label>
                    @(Html.For(model).TextBoxFor(x => x.ExteriorBase,ViewHelper.GetHtmlAttributes(disabled: !isAdmin)))
                    @(Html.For(model).ValidationMessageFor(x => x.ExteriorBase, null, new { @class = "text-danger" }))
                </div>
                <div class="form-group col-md-4">
                    <label for="shakesiding">Shake Siding</label>
                    @(Html.For(model).TextBoxFor(x => x.ShakeSiding,ViewHelper.GetHtmlAttributes(disabled: !isAdmin)))
                    @(Html.For(model).ValidationMessageFor(x => x.ShakeSiding, null, new { @class = "text-danger" }))
                </div>

                <div class="form-group col-md-4">
                    <label for="exteriortrim"> Exterior Trim</label>
                    @(Html.For(model).TextBoxFor(x => x.ExteriorTrim,ViewHelper.GetHtmlAttributes(disabled: !isAdmin)))
                    @(Html.For(model).ValidationMessageFor(x => x.ExteriorTrim, null, new { @class = "text-danger" }))
                </div>
            </div>

        <div class="row">
            <div class="form-group col-md-4">
                <label for="frontDoor">Front Door</label>
                @(Html.For(model).TextBoxFor(x => x.FrontDoor,ViewHelper.GetHtmlAttributes(disabled: !isAdmin)))
                @(Html.For(model).ValidationMessageFor(x => x.FrontDoor, null, new { @class = "text-danger" }))
            </div>
            <div class="form-group col-md-4">
                <label for="garageDoor">Garage Door</label>
                @(Html.For(model).TextBoxFor(x => x.GarageDoor,ViewHelper.GetHtmlAttributes(disabled: !isAdmin, maxLength: 50)))
                @(Html.For(model).ValidationMessageFor(x => x.GarageDoor, null, new { @class = "text-danger" }))
            </div>

            <div class="form-group col-md-4">
                <label for="stain">Stain</label>
                @(Html.For(model).TextBoxFor(x => x.Stain,ViewHelper.GetHtmlAttributes(disabled: !isAdmin, maxLength: 50)))
                @(Html.For(model).ValidationMessageFor(x => x.Stain, null, new { @class = "text-danger" }))
            </div>
        </div>


        <div class="row">
            <div class="form-group col-md-4">
                <label for="shutters">Shutters</label>
                @(Html.For(model).TextBoxFor(x => x.Shutters,ViewHelper.GetHtmlAttributes(disabled: !isAdmin, maxLength: 50)))
                @(Html.For(model).ValidationMessageFor(x => x.Shutters, null, new { @class = "text-danger" }))
            </div>

            <div class="form-group col-md-4">
                <label for="corbels">Corbels</label>
                @(Html.For(model).TextBoxFor(x => x.Corbels,ViewHelper.GetHtmlAttributes(disabled: !isAdmin, maxLength: 50)))
                @(Html.For(model).ValidationMessageFor(x => x.Corbels, null, new { @class = "text-danger" }))
            </div>

            <div class="form-group col-md-4">
                <label for="brackets">Brackets</label>
                @(Html.For(model).TextBoxFor(x => x.Brackets,ViewHelper.GetHtmlAttributes(disabled: !isAdmin, maxLength: 50)))
                @(Html.For(model).ValidationMessageFor(x => x.Brackets, null, new { @class = "text-danger" }))
            </div>
        </div>

        <div class="row">
            <div class="form-group col-md-4">
                <label for="handisiding">Hardi Siding</label>
                @(Html.For(model).TextBoxFor(x => x.HardiSiding,ViewHelper.GetHtmlAttributes(disabled: !isAdmin, maxLength: 50)))
                @(Html.For(model).ValidationMessageFor(x => x.HardiSiding, null, new { @class = "text-danger" }))
            </div>

            <div class="form-group col-md-4">
                <label for="boardandbatton">Board And Batton</label>
                @(Html.For(model).TextBoxFor(x => x.BoardAndBatton,ViewHelper.GetHtmlAttributes(disabled: !isAdmin, maxLength: 50)))
                @(Html.For(model).ValidationMessageFor(x => x.BoardAndBatton, null, new { @class = "text-danger" }))
            </div>

            <div class="form-group col-md-4">
                <label for="louvre">Louvre</label>
                @(Html.For(model).TextBoxFor(x => x.Louvre,ViewHelper.GetHtmlAttributes(disabled: !isAdmin, maxLength: 50)))
                @(Html.For(model).ValidationMessageFor(x => x.Louvre, null, new { @class = "text-danger" }))
            </div>
        </div>

        <div class="row">
            <div class="form-group col-md-4">
                <label for="accentstucco">Accent Base</label>
                @(Html.For(model).TextBoxFor(x => x.AccentBase,ViewHelper.GetHtmlAttributes(disabled: !isAdmin)))
                @(Html.For(model).ValidationMessageFor(x => x.AccentBase, null, new { @class = "text-danger" }))
            </div>

            <div class="form-group col-md-4">
                <label for="facia">Facia</label>
                @(Html.For(model).TextBoxFor(x => x.Facia,ViewHelper.GetHtmlAttributes(disabled: !isAdmin, maxLength: 50)))
                @(Html.For(model).ValidationMessageFor(x => x.Facia, null, new { @class = "text-danger" }))
            </div>
            <div class="form-group col-md-4">
                <label for="soffit">Soffit</label>
                @(Html.For(model).TextBoxFor(x => x.Soffit,ViewHelper.GetHtmlAttributes(disabled: !isAdmin)))
                @(Html.For(model).ValidationMessageFor(x => x.Soffit, null, new { @class = "text-danger" }))
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-12">
                <label for="Note">Note</label>
                @(Html.For(model).TextAreaFor(x => x.Note,ViewHelper.GetHtmlAttributes(disabled: !isAdmin, rows: 4)))
                @(Html.For(model).ValidationMessageFor(x => x.Note, null, new { @class = "text-danger" }))
            </div>
        </div>

        <div>
            <div class="form-group">
                @PageHelpers.CancelButton("ExteriorColorSchemes", "Communities")
                @if (model.Id > 0 && isAdmin)
                {
                    <button class="btn btn-danger"
                            data-execute="true"
                            data-url="@Url.Action("DeleteExteriorColorScheme", "Communities")"
                            data-data="@((new {id = model.Id}).ToJson())"
                            data-confirmmessage="Are you sure you want to permanently delete @Model.ViewModel.ExteriorBase?"
                            data-confirmtitle="Delete Color Scheme?"
                            data-redirect="@Url.Action("ExteriorColorSchemes", "Communities")">
                        Delete
                    </button>
                }

                @if (isAdmin)
                {
                    <input value="Save" type="submit" class="btn btn-primary" />
                }
            </div>
        </div>
    }
</section>

ImagePainting.Site.Web/Views/Communities/ExteriorColorSchemes.cshtml
@model SiteViewModel<List<ImagePainting.Site.Common.Models.ExteriorColorScheme>>

@{
    ViewBag.Title = "Exterior Color Schemes";
    ViewBag.CommunitiesActive = "active";
    var isAdmin = Model.UserHelper.IsUserAdmin();
}

<div class="jumbotron child">
    <h1>Exterior Color Schemes</h1>
</div>

<section class="container body-content">
    @if (isAdmin)
    {
    <div class="row add-container">
        <div class="col-md-12">
            @Html.ActionLink("New", "ExteriorColorScheme", "Communities", null, new { @class = "btn btn-primary pull-right" })

        </div>
    </div>
    }
    <table class="table data-table">
        <thead>
            <tr>
                <th>Color Code</th>
                <th>Exterior Base</th>
                <th>Exterior Trim</th>
                <th>Front Door</th>
                <th>Stain</th>
                <th>Garage Doors</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var colorScheme in Model.ViewModel)
            {
                <tr>
                    <td>@Html.ActionLink(colorScheme.ColorCode, "ExteriorColorScheme", "Communities", new { Id = colorScheme.Id }, null)</td>
                    <td>@colorScheme.ExteriorBase</td>
                    <td>@colorScheme.ExteriorTrim</td>
                    <td>@colorScheme.FrontDoor</td>
                    <td>@colorScheme.Stain</td>
                    <td>@colorScheme.GarageDoor</td>
                </tr>
            }
        </tbody>
    </table>
</section>

ImagePainting.Site.Web/Views/Communities/Index.cshtml
@model SiteViewModel<List<ImagePainting.Site.Common.Models.Community>>
@{
    ViewBag.Title = "Index";
    ViewBag.CommunitiesActive = "active";
    var isAdmin = Model.UserHelper.IsUserAdmin();

}

<div class="jumbotron child">
    <h1>Communities</h1>
</div>

<section class="container body-content">
    @if (isAdmin)
    {
    <div class="row add-container">
        <div class="col-md-12">
            @Html.ActionLink("Add", "Community", null, new { @class = "btn btn-primary pull-right" })

        </div>
     </div>
    }

    <table class="table table-striped data-table">
        <thead>
            <tr>
                <th>Active</th>
                <th>Community</th>
                <th>Builder(s)</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var community in Model.ViewModel)
            {
                foreach (var builder in community.Builders)
                {
                <tr>
                    <td>@(community.Active ? "Yes" : "No")</td>
                    <td>@Html.ActionLink(community.Name, "Community", new { id = community.Id })</td>
                    <td>
                        <span>@Html.ActionLink(builder.Name, "Builder", "Communities", new { id = builder.Id }, null)</span>
                    </td>
                </tr>
                }

                if (community.Builders.IsNullOrEmpty())
                {
                    <tr>
                        <td>@(community.Active ? "Yes" : "No")</td>
                        <td>@Html.ActionLink(community.Name, "Community", new { id = community.Id })</td>
                        <td></td>
                    </tr>
                }
            }
        </tbody>
    </table>
</section>

ImagePainting.Site.Web/Views/Communities/InteriorColorSchemes.cshtml
@model SiteViewModel<List<ImagePainting.Site.Common.Models.InteriorColorScheme>>

@{
    ViewBag.Title = "InteriorColorSchemes";
    ViewBag.CommunitiesActive = "active";
    var isAdmin = Model.UserHelper.IsUserAdmin();
}

<div class="jumbotron child">
    <h1>Interior Color Schemes</h1>
</div>

<section class="container body-content">
    @if (isAdmin)
    {
    <div class="row add-container">
        <div class="col-md-12">
           @Html.ActionLink("New", "InteriorColorScheme", "Communities", null, new { @class = "btn btn-primary pull-right" })

        </div>
    </div>
    }
    <table class="table data-table">
        <thead>
            <tr>
                <th>Color Code</th>
                <th>Interior Base</th>
                <th>Front Door</th>
                <th>Stain</th>
                <th>Interior Ceiling</th>
                <th>Interior Wood Trim Base/Casing</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var colorScheme in Model.ViewModel)
            {
                <tr>
                    <td>@Html.ActionLink(colorScheme.ColorCode, "InteriorColorScheme", "Communities", new { Id = colorScheme.Id }, null)</td>
                    <td>@colorScheme.InteriorBase</td>
                    <td>@colorScheme.FrontDoor</td>
                    <td>@colorScheme.Stain</td>
                    <td>@colorScheme.InteriorCeiling</td>
                    <td>@colorScheme.InteriorWoodTrimBaseCasing</td>
                </tr>
            }
        </tbody>
    </table>
</section>