ImagePainting.Site.Web/Controllers/PurchaseOrdersController.cs
using ImagePainting.Site.Common.Helpers;
using ImagePainting.Site.Common.Interfaces.Service;
using ImagePainting.Site.Common.Models;
using ImagePainting.Site.Web.Helpers;
using Newtonsoft.Json;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace ImagePainting.Site.Web.Controllers
{
    public class PurchaseOrdersController : BaseController
    {
        private readonly IPurchaseOrderService _purchaseOrderService;
        private readonly IPaintStoreService _paintStoreService;
        private readonly IWorkOrderMailer _worderOrderMailer;


        public PurchaseOrdersController(IPurchaseOrderService purchaseOrderService,
            IPaintStoreService paintStoreService, IWorkOrderMailer workOrderMailer,
            IViewHelper viewHelper,
            IUserHelper userHelper)
            : base(viewHelper, userHelper)
        {
            _purchaseOrderService = purchaseOrderService;
            _paintStoreService = paintStoreService;
            _worderOrderMailer = workOrderMailer;
        }
        
        public ActionResult PurchaseOrders(WorkOrderTask task, bool? emailed = null)
        {
            var purchaseOrdersTask = _purchaseOrderService.GetPurchaseOrders(task.Id, task.WorkOrderId, true, false, emailed: emailed);

            purchaseOrdersTask.Wait();

            if (emailed.HasValue)
            {
                return Json(purchaseOrdersTask.Result, JsonRequestBehavior.AllowGet);
            }

            ViewBag.workOrderTask = task;
            ViewBag.IsPartial = false;
            if (Request.IsAjaxRequest())
            {
                ViewBag.IsPartial = true;
            }

            return PartialView(purchaseOrdersTask.Result);
        }

        public async Task<ActionResult> WorkOrderPurchaseOrders(long id)
        {
            var purchaseOrders = await _purchaseOrderService.WorkOrderPurchaseOrders(id);

            return PartialView(purchaseOrders);
        }
        
        public async Task<ActionResult> UpdateViewWithRows(int taskId,int id, long? paintStoreId)
        {
            var model = await _purchaseOrderService.GetPurchaseOrder(taskId, id, paintStoreId);

            return PartialView2("_PurchaseOrder", model);
        }

        public async Task<ActionResult> PurchaseOrder(long taskId, long id)
        {
            var model = await _purchaseOrderService.GetPurchaseOrder(taskId, id);

            return View2(model);
        }

        [HttpPost]
        public async Task Delete(long id)
        {
           await _purchaseOrderService.DeletePurchaseOrder(id);
        }

        public async Task<ActionResult> ViewPurchaseOrder(long id)
        {
            var model = await _purchaseOrderService.GetPurchaseOrder(id, true);
            return PartialView(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> PurchaseOrder(PurchaseOrder order, bool sendEmail = false)
        {
            if (!ModelState.IsValid)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, JsonConvert.SerializeObject(ModelState));
            }

            var result = await _purchaseOrderService.SavePurchaseOrder(order, sendEmail);

            result.PurchaseOrderItems.ForEach(x => x.PurchaseOrder = null);

            if (Request.IsAjaxRequest())
            {
                return Json(result);
            }

            return RedirectToAction("PurchaseOrder", new { id = order.Id, taskId = order.TaskId });
        }

        public async Task<string> GetContactEmailForStoreLocation(long locationId)
        {
            var location = await _paintStoreService.GetStoreLocation(locationId);
            return location?.StoreContactEmail ?? string.Empty;
        }

        public ActionResult StoreLocation(long id)
        {
            var model = new PurchaseOrder
            {
                PaintStoreLocation = new StoreLocation { StoreId = id }
            };

            return PartialView(model);
        }
        
        [HttpPost]
        public async Task EmailPurchaseOrder(long id, string emailAddress)
        {
            await _worderOrderMailer.EmailPurchaseOrder(id, emailAddress);
            await _purchaseOrderService.UpdatePurchaseOrderEmailSent(id, emailAddress);
        }

        [HttpPost]
        public async Task<string> PreviewPurchaseOrder(long id)
        {
            var preview =  await _worderOrderMailer.PreviewPurchaseOrder(id).ConfigureAwait(false);
            return preview.ToJson();
        }

        [HttpPost]
        public async Task UnlockPurchaseOrder(long id)
        {
            await _purchaseOrderService.UnlockPurchaseOrder(id);
        }
    }
}

ImagePainting.Site.Web/Controllers/ReportsController.cs
using ImagePainting.Site.Common.Interfaces.Repository;
using ImagePainting.Site.Common.Models.Reports;
using ImagePainting.Site.Web.Helpers;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace ImagePainting.Site.Web.Controllers
{
    [Authorize(Roles = RolesConstant.Admin)]
    public class ReportsController : BaseController
    {
        private readonly IReportRepository _reportRepository;

        public ReportsController(
            IReportRepository reportRepository,
            IViewHelper viewHelper,
            IUserHelper userHelper)
            : base(viewHelper, userHelper)
        {
            _reportRepository = reportRepository;
        }

        public ActionResult PurchaseOrder()
        {
            var model = new List<PurchaseOrderReportItem>();

            return View2("Purchases", model);
        }
        
        public async Task<ActionResult> PurchaseOrderList(PurchaseReportQuery query)
        {
            var report = await _reportRepository.GetPurchaseReport(query);

            return PartialView("_PurchaseOrdersTable", report);
        }

        public ActionResult Tasks()
        {
            var model = new TasksReport();

            return View2(model);
        }

        public async Task<PartialViewResult> TasksReport(TasksReportQuery query)
        {
            var report = await _reportRepository.GetTasksReport(query);

            return PartialView("_TasksTable", report);
        }

        public ActionResult ProjectedRevenue()
        {
            var model = new ProjectedRevenueReport();

            return View2(model);
        }
        
        public async Task<PartialViewResult> ProjectedRevenueList(ProjectedRevenueReportQuery query)
        {
            var model = await _reportRepository.GetProjectedRevenueReport(query);

            return PartialView("_ProjectedRevenueTableList", model);
        }

        public ActionResult ProjectedLabor(ProjectedLaborReportQuery query)
        {
            var model = new ProjectedLaborReport();

            return View2(model);
        }

        public async Task<PartialViewResult> ProjectedLaborList(ProjectedLaborReportQuery query)
        {
            var report = await _reportRepository.GetProjectedLaborReport(query);

            return PartialView("_ProjectedLaborTableList", report);
        }
    }
}

ImagePainting.Site.Web/Controllers/TasksController.cs
using ImagePainting.Site.Common.Helpers;
using ImagePainting.Site.Common.Interfaces;
using ImagePainting.Site.Common.Interfaces.Repository;
using ImagePainting.Site.Common.Interfaces.Service;
using ImagePainting.Site.Common.Models;
using ImagePainting.Site.Common.Models.Enums;
using ImagePainting.Site.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using ImagePainting.Site.Web.Helpers;
using static ImagePainting.Site.Common.Helpers.DateHelper;
using static ImagePainting.Site.Web.Helpers.RolesConstant;

namespace ImagePainting.Site.Web.Controllers
{
    [Authorize]
    public class TasksController : BaseController
    {
        private readonly ITaskComposerService _taskService;
        private readonly IWorkOrderTaskManager _taskManager;
        private readonly ILogger _logger;
        private readonly IPurchaseOrderRepository _purchaseOrderRepository;
        private readonly IUserCacheService _userCacheService;
        private readonly IViewHelper _viewHelper;
        private readonly IUserHelper _userHelper;

        public TasksController(
            ITaskComposerService taskService,
            IWorkOrderTaskManager taskManager,
            ILogger logger,
            IUserCacheService userCacheService,
            IPurchaseOrderRepository purchaseOrderRepository,
            IViewHelper viewHelper, IUserHelper userHelper) : base(viewHelper, userHelper)

        {
            _taskService = taskService;
            _taskManager = taskManager;
            _logger = logger;
            _purchaseOrderRepository = purchaseOrderRepository;
            _userCacheService = userCacheService;
            _viewHelper = viewHelper;
            _userHelper = userHelper;
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            var tasks = await _taskService.GetTaskSchemas();
            return View(tasks);
        }

        [HttpGet, Authorize(Roles = Staff)]
        public async Task<ActionResult> Task(int id = 0)
        {
            var task = await _taskService.GetWorkSchemaTask(id);
            return View2(task);
        }

        [HttpGet, Authorize(Roles = Staff)]
        public async Task<ActionResult> ViewTask(int id)
        {
            var task = await _taskManager.GetTaskWithPermissions(id, true);

            if (!task.IsMainTask)
            {
                var mainTask = await _taskManager.GetMainTask(id);
                ViewBag.MainTaskId = mainTask.Id;
            }
            else
            {
                ViewBag.MainTaskId = task.Id;
            }

            return View2(task);
        }

        [HttpPost, Authorize(Roles = Staff)]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SaveWorkOrderTask(WorkOrderTask task)
        {
            var result = await _taskManager.SaveWorkOrderTask(task);

            if (Request.IsAjaxRequest())
            {
                result.RemovePermission();
                return Json(result);
            }

            return RedirectToAction("UpcomingTasks");
        }

        [HttpPost, Authorize(Roles = Staff)]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> UpdateTaskSchedule(TaskSchedule task)
        {
            var result = await _taskManager.UpdateTaskSchedule(task);
            result.RemovePermission();
            return Json(result);
        }

        [HttpPost, Authorize(Roles = Staff)]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Task(WorkOrderTaskSchema task)
        {
            if (!ModelState.IsValid)
            {
                return View2(task);
            }

            await _taskService.SaveTaskSchema(task);
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = Staff)]
        public Task<ActionResult> UpcomingTasks(int pageNumber = 0)
        {
            var today = GetLocalDateToday();
            var searchCriteria = new TaskSearchCriteria
            {
                IsUpcoming = true,
                IncludeCrew = true,
                IncludeWorkOrder = true,
                OrderByAscending = true,
                PageNumber = pageNumber,
                DateRange = new DateTimeRange
                {
                    BeginDateTime = today,
                    EndDateTime = today.AddDays(30)
                }
            };

            ViewBag.minDate = today;

            return CalendarView(searchCriteria, true);
        }

        [HttpGet]
        [Authorize(Roles = Staff)]
        public Task<ActionResult> CompletedTasks(int pageNumber = 0)
        {
            var today = GetLocalDateToday();
            var searchCriteria = new TaskSearchCriteria
            {
                IsCompleted = true,
                IncludeCrew = true,
                IncludeWorkOrder = true,
                OrderByAscending = false,
                PageNumber = pageNumber,
                DateRange = new DateTimeRange
                {
                    BeginDateTime = today.AddDays(-30),
                    EndDateTime = today
                }
            };

            return CalendarView(searchCriteria, true);
        }

        [HttpGet]
        [Authorize(Roles = Staff)]
        public Task<ActionResult> OverdueTasks(int pageNumber = 0)
        {
            var today = GetLocalDateToday();
            var searchCriteria = new TaskSearchCriteria
            {
                IsOverdued = true,
                IncludeCrew = true,
                IncludeWorkOrder = true,
                OrderByAscending = false,
                PageNumber = pageNumber,
                DateRange = new DateTimeRange
                {
                    BeginDateTime = today.AddDays(-30),
                    EndDateTime = today
                }
            };

            ViewBag.maxDate = today;

            return CalendarView(searchCriteria, true);
        }

        [HttpGet]
        [Authorize(Roles = Staff)]
        public Task<ActionResult> AllTasks(int pageNumber = 0)
        {
            var today = GetLocalDateToday();
            var searchCriteria = new TaskSearchCriteria
            {
                IncludeCrew = true,
                IncludeWorkOrder = true,
                OrderByAscending = true,
                PageNumber = pageNumber,
                DateRange = new DateTimeRange
                {
                    BeginDateTime = today.AddDays(-30),
                    EndDateTime = today
                }
            };

            return CalendarView(searchCriteria, true);
        }

        [HttpPost]
        [Authorize(Roles = Staff)]
        public async Task<ActionResult> LoadTasks(TaskSearchCriteria criteria)
        {
            var dateRange = criteria.ToDateRange();

            if (!criteria.CrewIds.IsNullOrEmpty())
            {
                criteria.CrewIds = CleanUpCrewIds(criteria.CrewIds.ToArray());
            }

            ViewBag.PageNumber = criteria.PageNumber;
            ViewBag.DateTimeRange = dateRange;

            criteria.IncludeCrew = true;
            criteria.IncludeCommunity = true;

            var viewModel = await GetCalendarViewModel2(criteria, dateRange);
            
            SetNavButtonsDisplay(criteria, dateRange);

            return PartialView("WorkOrderTasks", viewModel);
        }

        [HttpPost, Authorize(Roles = Staff)]
        public async Task<ActionResult> CompleteTask(WorkOrderTask task)
        {
            var result = await _taskManager.CompleteTask(task);

            result.RemovePermission();

            return Json(result);
        }

        [HttpPost, Authorize(Roles = Admin)]
        public async Task<ActionResult> UnlockTask(long id)
        {
            var result = await _taskManager.UnlockTask(id);

            result.RemovePermission();

            return Json(result);
        }

        [HttpPost, Authorize(Roles = Admin)]
        public async Task<ActionResult> DeferTask(long id)
        {
            await _taskService.SetTaskDeferState(id);

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        [HttpPost, Authorize(Roles = Admin)]
        public async Task EmailScheduleTask(IEnumerable<long> ids, string note, FreeCrewViewModel freeCrewsModel)
        {
            if (!freeCrewsModel.FreeCrewIds.IsNullOrEmpty())
            {
                await _taskService.SendNoTaskEmailAsync(freeCrewsModel.FreeCrewIds, freeCrewsModel.TaskDate, freeCrewsModel.Note);
            }

            if (!ids.IsNullOrEmpty())
            {
                await _taskService.SendWorkOrderMails(ids, note);
            }
        }

        [HttpPost, Authorize(Roles = Admin)]
        public async Task<ActionResult> DeleteTaskSchema(int id)
        {
            try
            {
                await _taskService.DeleteTaskSchema(id);
            }
            catch (Exception ex)
            {
                _logger.Error(ex);

                var msg = "Deleting task schema failed!";

                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, msg);
            }

            return Json(new { Success = true });
        }

        [HttpPost, Authorize(Roles = Admin)]
        public async Task<JsonResult> UpdateUnassignedCrewStatus(string crewId, DateTime scheduledDate, bool status)
        {
            await _taskService.UpdateUnAssignedCrewSetting(new List<string>{crewId}, scheduledDate, busy: status);

            return Json(new {Success = true});
        }

        [HttpGet]
        public async Task<JsonResult> GetBusyUser(string crewId, DateTime date)
        {
            var user = await _taskService.GetBusyUser(crewId, date);

            return Json(user, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public async Task<JsonResult> GetTaskPdfTemplate(long taskId)
        {

ImagePainting.Site.Web/Views/Reports/ProjectedLabor.cshtml
@model SiteViewModel<ImagePainting.Site.Common.Models.Reports.ProjectedLaborReport>

@{
    ViewBag.Title = "Projected Labor Report";
    ViewBag.ReportActive = "active";
}

<div class="jumbotron child">
    <h1>Projected Labor Report</h1>
</div>

<section class="container body-content">
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default" style="overflow:visible">
            <div class="panel-heading" role="tab" id="headingOne">
                <h4 class="panel-title">
                    <a role="button" class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#searchCollapse" aria-expanded="true" aria-controls="collapseOne">
                        Search
                    </a>
                </h4>
            </div>
            <form id="searchCollapse" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                    <div class="panel-body">
                        <div class="row">
                            <div class="form-group col-md-4">
                                <label>Builder</label>
                                @Html.DropDownList("BuilderId", Model.ViewHelper.GetSingleBuilderOptions(),ViewHelper.GetHtmlAttributes())
                            </div>
                            <div class="form-group col-md-4" id="communities">
                                @{ Html.RenderAction("Communities", "WorkOrders", new { showCreateOption = false, showBlankOption = true }); }
                            </div>
                            <div class="form-group col-md-4" id="plans">
                                @{ Html.RenderAction("Plans", "WorkOrders", new { id = 0, showCreateOption = false }); }
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-4">
                                <label>Crew</label>
                                @Html.DropDownList("CrewIds",
                                      Model.ViewHelper.GetUsersOptions(includeBlankOption: false, includeUnassigned: false),
                                     ViewHelper.GetHtmlAttributes(multiple: true, id: "CrewIds"))
                            </div>
                            <div class="form-group col-md-4">
                                <label class="required-field">Date From</label>
                                @Html.TextBox("DateRange.BeginDateTime", null,ViewHelper.GetHtmlAttributes(type: "date", @class: "required"))
                                @Html.ValidationMessage("DateRange.BeginDateTime")
                            </div>
                            <div class="form-group col-md-4">
                                <label class="required-field">Date To</label>
                                @Html.TextBox("DateRange.EndDateTime", null,ViewHelper.GetHtmlAttributes(type: "date", @class: "required"))
                                @Html.ValidationMessage("DateRange.EndDateTime")
                            </div>
                        </div>
                    </div>
                    <div class="container-fluid">
                        <div class="panel-footer">
                            <button class="btn btn-default" id="searchBtn" type="button">Search</button>
                        </div>
                    </div>
            </form>
        </div>
    </div>
    <br />
    <div class="table-responsive" id="tableDiv">
        @Html.Partial("_ProjectedLaborTableList", Model.ViewModel)
    </div>

    @section scripts {
        @Scripts.Render("~/bundles/bootstrapmultiselect");
        @Scripts.Render("~/bundles/reports")
        <script>
            $(app.reports.initMultiSelect)
            $(app.reports.initLaborReport)
        </script>
    }
</section>

ImagePainting.Site.Web/Views/Reports/ProjectedRevenue.cshtml
@model SiteViewModel<ImagePainting.Site.Common.Models.Reports.ProjectedRevenueReport>

@{
    ViewBag.Title = "Projected Revenue Report";
    ViewBag.ReportActive = "active";
}

<div class="jumbotron child">
    <h1>Projected Revenue Report</h1>
</div>

<section class="container body-content">
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingOne">
                <h4 class="panel-title">
                    <a role="button" class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#searchCollapse" aria-expanded="true" aria-controls="collapseOne">
                        Search
                    </a>
                </h4>
            </div>
            <form id="searchCollapse" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                <div class="panel-body">
                    <div class="row">
                        <div class="form-group col-md-4">
                            <label class="required-field">Date From</label>
                            @Html.TextBox("DateRange.BeginDateTime", null, ViewHelper.GetHtmlAttributes(type: "date", @class: "required"))
                            @Html.ValidationMessage("DateRange.BeginDateTime")
                        </div>
                        <div class="form-group col-md-4">
                            <label class="required-field">Date To</label>
                            @Html.TextBox("DateRange.EndDateTime", null, ViewHelper.GetHtmlAttributes(type: "date", @class: "required"))
                            @Html.ValidationMessage("DateRange.EndDateTime")
                        </div>
                        <div class="form-group col-md-4">
                            <label>Builder</label>
                            @Html.DropDownList("BuilderId", Model.ViewHelper.GetSingleBuilderOptions(), ViewHelper.GetHtmlAttributes(@class: "form-control"))
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-4" id="communities">
                            @{ Html.RenderAction("Communities", "WorkOrders", new { showCreateOption = false, showBlankOption = true }); }
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="panel-footer">
                        <button class="btn btn-default" id="searchBtn" type="button">Search</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <br />
    <div id="tableDiv" class="table-responsive">
        @Html.Partial("_ProjectedRevenueTableList", Model.ViewModel)
    </div>
</section>

@section scripts {
    @Scripts.Render("~/bundles/reports")

    <script>
        $(app.reports.initRevenueReport)
    </script>
}

ImagePainting.Site.Web/Views/Reports/_ProjectedLaborTableList.cshtml
@using System.Globalization;
@model ImagePainting.Site.Common.Models.Reports.ProjectedLaborReport

@{
    var numberFormat = (NumberFormatInfo)CultureInfo.CurrentCulture.NumberFormat.Clone();
    numberFormat.CurrencyNegativePattern = 1;
}
<table id="tasks" class="table table-condensed table-striped">
    <thead>
        <tr>
            <th>Task</th>
            <th>Work Order</th>
            <th>Lot & Block</th>
            <th>Crew</th>
            <th>Builder</th>
            <th>Community</th>
            <th>Amount</th>
            <th>Completed</th>
            <th>Prewalk</th>
            <th>Completion Walk</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var laborReportItem in Model.LaborReportItems)
        {
            if (laborReportItem.Amount != 0)
            {
            <tr>
                <td>@Html.ActionLink(laborReportItem.Task, "ViewTask", "Tasks", new { id = laborReportItem.TaskId }, new { @class = "task-name" })</td>
                <td>@Html.ActionLink(laborReportItem.WorkOrder, "WorkOrder", "WorkOrders", new { id = laborReportItem.WorkOrderId }, string.Empty)</td>
                <td>@("Lot# " + laborReportItem.Lot + " Block " + laborReportItem.Block)</td>
                <td>@laborReportItem.Crew</td>
                <td>@Html.ActionLink(laborReportItem.Builder, "Builder", "Communities", new { id = laborReportItem.BuilderId }, string.Empty)</td>
                <td>@Html.ActionLink(laborReportItem.Community, "Community", "Communities", new { id = laborReportItem.CommunityId }, string.Empty)</td>
                <td>@laborReportItem.Amount.ToString("C", numberFormat)</td>
                <td>@(laborReportItem.Completed.HasValue ? laborReportItem.Completed.Value.ToLocalShortDate() : string.Empty)</td>
                <td>@(laborReportItem.PreWalk.HasValue ? laborReportItem.PreWalk.Value.ToLocalShortDate() : string.Empty)</td>
                <td>@(laborReportItem.CompletionWalk.HasValue ? laborReportItem.CompletionWalk.Value.ToLocalShortDate() : string.Empty)</td>
            </tr>
            }
        }
    </tbody>
    @if (Model.LaborReportItems.Count() > 0)
    {
        <tfoot>
            <tr>
                <th colspan="6">Total</th>
                <th>@Model.TotalAmount.ToString("C", numberFormat)</th>
                <th colspan="3"></th>
            </tr>
        </tfoot>
    }
</table>

ImagePainting.Site.Web/Views/Reports/_ProjectedRevenueTableList.cshtml
@model ImagePainting.Site.Common.Models.Reports.ProjectedRevenueReport

<table class="table table-condensed table-striped">
    <thead>
        <tr>
            <th>WorkOrder</th>
            <th>Lot</th>
            <th>Block</th>
            <th>Community</th>
            <th>Builder</th>
            <th>Revenue Total</th>
            <th>Completed</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var report in Model.RevenueReportItems)
        {
            <tr>
                <td>@Html.ActionLink(@report.WorkOrder, "WorkOrder", "WorkOrders", new { id = report.WorkOrderId}, null)</td>
                <td>@report.Lot</td>
                <td>@report.Block</td>
                <td>@report.Community</td>
                <td>@report.Builder</td>
                <td>@report.TotalRevenue.ToString("C")</td>
                <td>@(report.Completed.HasValue ? report.Completed.Value.ToLocalShortDate() : string.Empty)</td>
            </tr>
        }
    </tbody>
    @if (Model.RevenueReportItems.Count() > 0)
    {
        <tfoot>
            <tr>
                <th colspan="5">Total</th>
                <th>@Model.TotalRevenue.ToString("C")</th>
                <th></th>
            </tr>
        </tfoot>
    }
</table>

ImagePainting.Site.Web/Views/Reports/_PurchaseOrdersTable.cshtml
@model IEnumerable<ImagePainting.Site.Common.Models.Reports.PurchaseOrderReportItem>

<table class="table table-condensed table-striped ">
    <thead>
        <tr>
            <th>Purchase Order</th>
            <th>Work Order</th>
            <th>Task</th>
            <th>Task Type</th>
            <th>Lot & Block</th>
            <th>Crew</th>
            <th>Store</th>
            <th>Builder</th>
            <th>Community</th>
            <th>Total</th>
            <th>Emailed</th>
        </tr>
    </thead>
    <tbody>
        
        @foreach (var report in Model)
        {
            <tr>
                <td>@report.PurchaseOrder.PoNumber</td>
                @*<td>@(Html.ActionLink(report.PurchaseOrder.PoNumber, "PurchaseOrder", "PurchaseOrders", new { id = report.PurchaseOrder.Id, taskId = report.Task.Key }, null))</td>*@
                <td>@(Html.ActionLink(report.WorkOrder.Value, "WorkOrder", "WorkOrders", new { id = report.WorkOrder.Key }, null))</td>
                <td>@(Html.ActionLink(report.Task.Value, "ViewTask", "Tasks", new { id = report.Task.Key }, null))</td>
                <td>@report.TaskType</td>
                <td>@($"Lot #{report.Lot} Block {report.Block}")</td>
                <td>@report.Crew</td>
                <td>@(Html.ActionLink(report.Store.Value, "Store", "PaintStores", new { id = report.Store.Key }, null))</td>
                <td>@(Html.ActionLink(report.Builder.Value, "Builder", "Communities", new { id = report.Builder.Key }, null))</td>
                <td>@(Html.ActionLink(report.Community.Value, "Community", "Communities", new { id = report.Community.Key }, null))</td>
                <td>@report.Total</td>
                <td>@(report.EmailSent.HasValue ? report.EmailSent.Value.ToLocalShortDate() : string.Empty) </td>
            </tr>
        }
       
    </tbody>
</table>

ImagePainting.Site.Web/Views/Reports/_TasksTable.cshtml
@model ImagePainting.Site.Common.Models.Reports.TasksReport

<table id="tasks" class="table table-condensed table-striped">
    <thead>
        <tr>
            <th>Task</th>
            <th>Work Order</th>
            <th>Lot</th>
            <th>Block</th>
            <th>Crew</th>
            <th>Builder</th>
            <th>Community</th>
            <th>Completed</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var taskRecord in Model.TaskReportItems)
        {
            <tr>
                <td>@Html.ActionLink(taskRecord.Task, "ViewTask", "Tasks", new { id = taskRecord.TaskId }, new { @class = "task-name" })</td>
                <td>@Html.ActionLink(taskRecord.WorkOrder, "WorkOrder", "WorkOrders", new { id = taskRecord.WorkOrderId }, string.Empty)</td>
                <td>@taskRecord.Lot</td>
                <td>@taskRecord.Block</td>
                <td>@taskRecord.Crew</td>
                <td>@Html.ActionLink(taskRecord.Builder, "Builder", "Communities", new { id = taskRecord.BuilderId }, string.Empty)</td>
                <td>@Html.ActionLink(taskRecord.Community, "Community", "Communities", new { id = taskRecord.CommunityId }, string.Empty)</td>
                <td>@(taskRecord.Completed.HasValue ? taskRecord.Completed.Value.ToLocalShortDate() : string.Empty)</td>
            </tr>
        }
    </tbody>
</table>