ImagePainting.Site.Web/Controllers/FileUploadsController.cs
using ImagePainting.Site.Common.Interfaces;
using ImagePainting.Site.Common.Interfaces.Repository;
using ImagePainting.Site.Common.Models;
using ImagePainting.Site.Common.Models.Enums;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using static ImagePainting.Site.Web.Helpers.RolesConstant;
using ImagePainting.Site.Web.Helpers;

namespace ImagePainting.Site.Web.Controllers
{
    public class FileUploadsController : BaseController
    {
        private readonly IFileUploadRepository _fileUploadRepository;
        private readonly IUserContext _userContext;

        public FileUploadsController(
            IFileUploadRepository fileUploadRepository, 
            IUserContext userContext,
            IViewHelper viewHelper,
            IUserHelper userHelper) : base(viewHelper, userHelper)
        {
            _fileUploadRepository = fileUploadRepository;
            _userContext = userContext;
        }

        [HttpGet]
        public async Task<FileContentResult> File(long id)
        {
            var fileUpload = await _fileUploadRepository.GetFileUpload(id);

            if (fileUpload == null)
            {
                throw new ArgumentException($"{id} is not a valid file upload ID");
            }

            SecuredFileValidation(fileUpload);

            return File(fileUpload.Content, fileUpload.ContentType);
        }

        public PartialViewResult Files(long ownerId, FileOwnerType ownerType, FileOwnerType? secondaryOwnerType = null)
        {

            var filesTask = _fileUploadRepository.GetFileUploads(ownerId, ownerType, secondaryOwnerType ?? FileOwnerType.Unknown);

            filesTask.Wait();

            ViewBag.OwnerId = ownerId;
            ViewBag.OwnerType = (int)ownerType;

            return PartialView2(filesTask.Result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Upload(long ownerId, FileOwnerType ownerType)
        {
            var fileUploads = new List<FileUpload>();
            var dateNow = DateTime.UtcNow;
            var userId = _userContext.UserId;
            
            foreach(var fileKey in Request.Files.AllKeys)
            {
                var file = Request.Files[fileKey];
                var fileUpload = new FileUpload { OwnerId = ownerId, OwnerType = ownerType };

                using (var reader = new BinaryReader(file.InputStream))
                {
                    fileUpload.Content = reader.ReadBytes(file.ContentLength);
                }

                fileUpload.ContentType = file.ContentType;
                fileUpload.Name = file.FileName;
                fileUpload.CreatedById = userId;
                fileUpload.Created = dateNow;

                fileUploads.Add(fileUpload);
            }

            if (fileUploads.Any())
            {
                await _fileUploadRepository.CreateFileUploads(fileUploads);
            }

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        [HttpPost]
        public async Task Delete(long id)
        {
            await _fileUploadRepository.DeleteFileUpload(id);
        }

        private void SecuredFileValidation(FileUpload fileUpload)
        {
            if (fileUpload.OwnerType == FileOwnerType.SecuredWorkOrder && !_userContext.IsAdmin())
            {
                throw new Exception($"User does not have permission to download file {fileUpload.Name}");
            }
        }
    }
}

ImagePainting.Site.Web/Controllers/WorkOrdersController.cs
using ImagePainting.Site.Common.Helpers;
using ImagePainting.Site.Common.Interfaces.Repository;
using ImagePainting.Site.Common.Interfaces.Service;
using ImagePainting.Site.Common.Models;
using ImagePainting.Site.Common.Models.Enums;
using ImagePainting.Site.Common.ViewModels;
using ImagePainting.Site.Web.Helpers;
using ImagePainting.Site.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using static ImagePainting.Site.Web.Helpers.RolesConstant;

namespace ImagePainting.Site.Web.Controllers
{
    [Authorize(Roles = Staff)]
    public class WorkOrdersController : BaseController
    {
        private readonly IWorkOrderComposerService _workOrderService;
        private readonly IWorkOrderTaskManager _taskManager;
        private ILogger _logger;
        private readonly IWorkOrderMailer _workOrderMailer;
        private readonly IUserHelper _userHelper;

        public WorkOrdersController(
            IWorkOrderComposerService workOrderService,
            IWorkOrderTaskManager taskManager,
            ILogger logger,
            IWorkOrderMailer workOrderMailer,
            IViewHelper viewHelper,
            IUserHelper userHelper)
            : base(viewHelper, userHelper)
        {
            _workOrderService = workOrderService;
            _taskManager = taskManager;
            _workOrderMailer = workOrderMailer;
            _logger = logger;
            _userHelper = userHelper;
        }

        [Authorize(Roles = Admin)]
        public async Task<ActionResult> Index()
        {
            var query = new WorkOrderQuery();
            var result = await _workOrderService.SearchWorkOrders(query);

            return View2(result);
        }

        [HttpPost]
        [Authorize(Roles = Admin)]
        public async Task<ActionResult> DeleteWorkOrder(long id)
        {
            try
            {
                await _workOrderService.DeleteWorkOrder(id);
            }

            catch(Exception ex)
            {
                _logger.Error(ex);

                var msg = "Deleting work order failed!";

                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, msg);
            }

            return Json(new { Success = true });
        }

        [HttpGet]
        public PartialViewResult Complete()
        {
            return PartialView();
        }

        [HttpPost, Authorize(Roles = Admin)]
        public async Task Complete(long id)
        {
            await _workOrderService.CompleteWorkOrder(id);
        }

        [HttpPost]
        public async Task<PartialViewResult> WorkOrderList(WorkOrderQuery sortSummary)
        {
            var result = await _workOrderService.SearchWorkOrders(sortSummary);

            return PartialView2("_WorkOrderList", result);
        }

        public ActionResult WorkOrder(long id = 0)
        {
            return View2(id);
        }

        public async Task<string> WorkOrderDetails(long id)
        {
            var workOrder = await _workOrderService.GetWorkOrder(id, true);

            // TODO: result json result instead of string
            return workOrder.ToJson();
        }

        public async Task<PartialViewResult> InitialSettings(int id = 0)
        {
            var model = await _workOrderService.GetInitialSettingsModel(id);
            ViewBag.workOrderCompleted = model.WorkOrderCompleted;
            
            return PartialView2(model.Item);
        }

        public async Task<JsonResult> WorkOrderExists(int id, string name)
        {
            var result = await _workOrderService.WorkOrderExists(id, name);

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult Communities(int? id, bool showCreateOption = true, bool showBlankOption = true)
        {
            var model = new WorkflowInitalSettingsViewModel
            {
                 BuilderId = id 
            };
            ViewData["showCreateOption"] = showCreateOption;
            ViewData["showBlankOption"] = showBlankOption;
            
            return PartialView2(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Admin)]
        public async Task<JsonResult> SaveInitialSettings(WorkflowInitalSettingsViewModel model)
        {
            var workOrder = await _workOrderService.SaveInitialSettings(model);

            return Json(workOrder);
        }

        public async Task<ActionResult> JobInfo(long id = 0, bool? colorsOnly = null)
        {
            var model = await _workOrderService.GetJobInfo(id);
            ViewBag.WorkOrderCompleted = model.WorkOrderCompleted;
            ViewBag.BuilderId = model.BuilderId;
            ViewBag.ColorCodePrefix = model.BuilderAbbrevation;
            ViewBag.WorkOrderId = id;

            if (colorsOnly.HasValue && colorsOnly.Value)
            {
                var colorsList = new List<KeyValuePair<string, string>> {
                    new KeyValuePair<string, string>("Exterior", model.Item.ExteriorColors.ToJson()),
                    new KeyValuePair<string, string>("Interior", model.Item.InteriorColors.ToJson())
                };

                return Json(colorsList, JsonRequestBehavior.AllowGet);
            }
            
            return PartialView2(model.Item);
        }

        public PartialViewResult Plans(int? id, int? planId, bool showCreateOption = true)
        {
            ViewData["BuilderId"] = id;
            ViewData["showCreateOption"] = showCreateOption;

            var model = new JobInfo
            {
                 PlanId = planId 
            };

            return PartialView2(model);
        }
        
        public PartialViewResult Elevations(int id)
        {
            var model = new JobInfo
            {
                PlanId = id 
            };
            
            return PartialView2(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Admin)]
        public async Task<JsonResult> SaveJobInfo(long workOrderId, JobInfo jobInfo)
        {
            var result = await _workOrderService.SaveJobInfo(workOrderId, jobInfo);

            return Json(result.Id);
        }

        public async Task<PartialViewResult> ExtraJob(long id)
        {
            var workOrderItemVM = await _workOrderService.GetExtraJobInfo(id);
            var isAdmin = _userHelper.IsUserAdmin();
            var viewName = isAdmin ? "ExtraJob" : "ExtraJob_Disabled";
            
            var viewModel = isAdmin ? new JobExtraViewModel
            {
                Id = workOrderItemVM.Item.Id,
                Note = workOrderItemVM.Item.Note,
                ExtraItems = workOrderItemVM.Item.ExtraItems,
                WorkOrderCompleted = workOrderItemVM.WorkOrderCompleted,
                WorkOrderId = id,
                IsAdmin = isAdmin
            } : ExtraJobInfoViewBuilder.BuildView(id, workOrderItemVM);
            
            return PartialView2(viewName, viewModel);
        }

        public async Task<JsonResult> AllExtraItems(long id)
        {
            var items = await _workOrderService.GetAllJobExtras(id);

            return Json(items, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Admin)]
        public async Task<long> ExtraJob(long workOrderId, ExtraJobInfo extraJobInfo)
        {
            var newExtraJobInfo = await _workOrderService.SaveExtraJobInfo(workOrderId, extraJobInfo);
            await _workOrderMailer.EmailProjection(workOrderId);
            
            return newExtraJobInfo.Id;
        }

        [HttpGet]
        [Authorize(Roles = Admin)]
        public async Task<PartialViewResult> ScheduleTasks(long id)
        {
            var model = await _taskManager.GetTaskSchedules(id);
            
            return PartialView2(model.ToList());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Admin)]
        public async Task<JsonResult> ScheduleTasks(long id, IEnumerable<ScheduleWorkOrderTask> model)
        {
            var result = await _workOrderService.ScheduleTask(id, model);
            
            return Json(result);
        }

        /// <summary>
        /// Gets Scheduled Task
        /// </summary>
        /// <param name="id">Task Id</param>
        public async Task<PartialViewResult> Task(long id)
        {
            var model = await _taskManager.GetTaskWithPermissions(id);

            return PartialView2(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Staff)]
        public async Task Task(WorkOrderTask model)
        {
            await _workOrderService.SaveWorkOrderTask(model);
        }

        [HttpGet]
        [Authorize(Roles = Staff)]
        public ActionResult TaskLaborPricing(long taskId)
        {
            var model = _workOrderService.GetTaskPricing(taskId);
            
            return PartialView(model);
        }

        [HttpPost]
        [Authorize(Roles = Admin)]
        public async Task<long> CloneWorkOrder(long id)
        {
            return await _workOrderService.CloneWorkOrder(id);
        }

        [HttpGet]
        [Authorize(Roles = AdminAndEmployee)]
        public async Task<PartialViewResult> Notes(long id)
        {
            var notes = await _workOrderService.GetNotes(id);

            return PartialView(notes);
        }

        [HttpPost, Authorize(Roles = Admin)]
        public async Task ChangeExtraItemTaskType(long id, string extraItemName, TaskType taskType, List<long> taskIds)
        {
            await _workOrderService.ChangeExtraItemTaskType(id, extraItemName, taskType, taskIds);
        }

        [HttpGet, Authorize(Roles = Admin)]
        public ActionResult WorkItems(long taskId)
        {

ImagePainting.Site.Web/Views/WorkOrders/Communities.cshtml
@model SiteViewModel<WorkflowInitalSettingsViewModel>

@{
    var model = Model.ViewModel;
    var workOrderCompleted = ViewData.ContainsKey("workOrderCompleted") ? (bool)ViewData["workOrderCompleted"] : false;
    var showCreate = ViewData.ContainsKey("showCreateOption") ? (bool)ViewData["showCreateOption"] : true;
    var showNewOption = ViewData.ContainsKey("showBlankOption") ? (bool)ViewData["showBlankOption"] : true;
    var isDisabled = !Model.UserHelper.IsUserAdmin() || !Model.ViewModel.BuilderId.HasValue || workOrderCompleted;
}

<label class="required-field">Community</label>
@Html.For(model).DropDownListFor(x => x.CommunityId, Model.ViewHelper.GetCommunityOptions(model.CommunityId ?? 0, includeBlankOption: showNewOption, includeNewOption: showCreate, builderId: model.BuilderId), ViewHelper.GetHtmlAttributes(disabled: isDisabled))
@Html.For(model).ValidationMessageFor(x => x.CommunityId)

ImagePainting.Site.Web/Views/WorkOrders/Complete.cshtml
<h3> Completion</h3>
<section class="wo-step-screen" data-node="completion">
    <form action="@Url.Action("Complete", "WorkOrders", FormMethod.Post)" novalidate>
        @Html.AntiForgeryToken()
        @Html.Hidden("Id")
        <label class="check">
           @Html.CheckBox("Complete", new { id = "complete-checkbox" })
            <span class="animated-checkbox">
            <i class="animated-checkbox-icon glyphicon glyphicon-ok"></i>
            </span>
            Set Work Order Complete
        </label>
        <div class="form-group">
            <input type="submit" value="Save" id="btn-continue" class="btn btn-primary" />
        </div>
    </form>

    <script>
        $(app.workorders.completeWorkOrder);
    </script>
</section>
        

ImagePainting.Site.Web/Views/WorkOrders/FileUploads.cshtml
@model Dictionary<string, IEnumerable<FileUpload>>
@{
    var redirectUrl = $"/WorkOrders/WorkOrder/{Request.Url.Segments.Last()}#{Request.Url.AbsolutePath}|workorders";
    redirectUrl = Request.Url.AbsolutePath;
}
<div class="wo-step-screen table-responsive" data-node="fileUploads">
    <h3>File Uploads</h3>

    @if (Model.Count == 0)
    {
        <p>There are no uploaded files for this work order.</p>
    }

    @foreach (var group in Model)
    {
        <div class="panel panel-default">
            <div class="panel-heading">@group.Key</div>
            <div class="panel-body">
                <div>
                    @Html.Hidden("files-list-url", Url.Action("Files", "FileUploads", new { ownerId = ViewBag.OwnerId, ownerType = ViewBag.OwnerType }))
                    <ul class="list-group">
                        @foreach (var fileUpload in group.Value)
                        {
                            <li class="list-group-item">
                                <a href="#deleteFile" class="pull-right text-danger"
                                   data-execute="true"
                                   data-url="@Url.Action("Delete", "FileUploads")"
                                   data-data="@((new {id = fileUpload.Id}).ToJson())"
                                   data-confirmmessage='Are you sure you want to delete "@fileUpload.Name"?'
                                   data-confirmtitle="Delete File?"
                                   data-onExecute="app.workorders.reloadWorkOrderFileslist('@redirectUrl')">
                                    <span class="glyphicon glyphicon-remove"></span>
                                </a>
                                @Html.ActionLink(fileUpload.Name, "File", "FileUploads", new { id = fileUpload.Id }, new { @target = "_blank" })
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    }

    <button class="btn btn-primary" id="btn-continue">Continue</button>

    <script>
        $(app.workorders.initFileUploads);
    </script>
</div>

ImagePainting.Site.Web/Views/WorkOrders/InitialSettings.cshtml
@model SiteViewModel<WorkflowInitalSettingsViewModel>
@{
    var workOrderCompleted = ViewBag.workOrderCompleted ? true : false;
    var model = Model.ViewModel;
    var isAdmin = Model.UserHelper.IsUserAdmin(); var isDisabled = !isAdmin || workOrderCompleted;
    var showSecuredUpload = isAdmin && model.WorkOrderId > 0;
    var excludeNoSuperintendent = true;
}

<div class="wo-step-screen" id="initialSettings" data-node="settings">
    <form action="@Url.Action("SaveInitialSettings", "WorkOrders")">
        @Html.AntiForgeryToken()
        <h3>Select Builder &amp; Community</h3>

        @(Html.For(model).HiddenFor(x => x.WorkOrderId))

        <div class="form-group" id="wo-builder">
            <label class="required-field">Builder</label>
            @Html.For(model).DropDownListFor(x => x.BuilderId, Model.ViewHelper.GetBuilderOptions(new List<int> { model.BuilderId ?? 0 }, true), ViewHelper.GetHtmlAttributes(disabled: isDisabled, id: "BuilderId"))
            @Html.For(model).ValidationMessageFor(x => x.BuilderId)
        </div>
        <div class="form-group" id="wo-community">
            @Html.Partial("Communities", Model, new ViewDataDictionary { { "workOrderCompleted", workOrderCompleted }, { "showCreateOption", true } })
        </div>

        <div class="row">
            <div class="col-md-6 form-group">
                <label class="required-field">Lot</label>
                @Html.For(model).TextBoxFor(x => x.Lot,ViewHelper.GetHtmlAttributes(type: "number", maxLength: 20, disabled: isDisabled, id: "Lot"))
                @Html.For(model).ValidationMessageFor(x => x.Lot)
            </div>
            <div class="col-md-6 form-group">
                <label class="required-field">Block</label>
                @Html.For(model).TextBoxFor(x => x.Block,ViewHelper.GetHtmlAttributes(maxLength: 20, disabled: isDisabled, id: "Block"))
                @Html.For(model).ValidationMessageFor(x => x.Block)
            </div>
        </div>

        <div class="form-group">
            <label class="required-field">Work Order Name</label>
            @Html.For(model).TextBoxFor(x => x.Name,ViewHelper.GetHtmlAttributes(maxLength: 128, disabled: isDisabled, id: "Name"))
            @Html.For(model).ValidationMessageFor(x => x.Name)
        </div>

        <div class="form-group">
            <label>Address</label>
            @Html.For(model).TextBoxFor(x => x.Address,ViewHelper.GetHtmlAttributes(maxLength: 256, disabled: isDisabled))
            @Html.For(model).ValidationMessageFor(x => x.Address)
        </div>

        <div class="form-group">
            <label>Superintendent</label>
            @Html.For(model).DropDownList("SuperintendentList", Model.ViewHelper.GetSuperintendentOptions(excludeNoSuperintendent),ViewHelper.GetHtmlAttributes(maxLength: 256, formControl: true, disabled: isDisabled, @class: "superintendent-list"))
            @Html.For(model).TextBoxFor(x => x.SuperIntendent,ViewHelper.GetHtmlAttributes(maxLength: 256, formControl: true, disabled: isDisabled, @class: "item-superintendent"))
            @Html.For(model).ValidationMessageFor(x => x.SuperIntendent)
        </div>

        <div class="form-group">
            <label>Customer Rep</label>
            @Html.For(model).DropDownList("CustomerRepList", Model.ViewHelper.GetCustomerRepOptions(),ViewHelper.GetHtmlAttributes(maxLength: 256, formControl: true, disabled: isDisabled, @class: "customer-reps-list"))
            @Html.For(model).TextBoxFor(x => x.CustomerRep,ViewHelper.GetHtmlAttributes(maxLength: 256, formControl: true, disabled: isDisabled, @class: "item-customer-rep"))
            @Html.For(model).ValidationMessageFor(x => x.CustomerRep)
        </div>

        <div class="form-group">
            <label>Customer Name</label>
            @Html.For(model).TextBoxFor(x => x.CustomerName,ViewHelper.GetHtmlAttributes(maxLength: 50, disabled: isDisabled))
            @Html.For(model).ValidationMessageFor(x => x.CustomerName)
        </div>

        <div class="form-group">
            <label>Customer Phone #</label>
            @Html.For(model).TextBoxFor(x => x.CustomerPhoneNumber,ViewHelper.GetHtmlAttributes(maxLength: 16, disabled: isDisabled))
            @Html.For(model).ValidationMessageFor(x => x.CustomerPhoneNumber)
        </div>

        <div class="form-group">
            <label>Customer Email</label>
            @Html.For(model).TextBoxFor(x => x.CustomerEmail,ViewHelper.GetHtmlAttributes(maxLength: 128, disabled: isDisabled))
            @Html.For(model).ValidationMessageFor(x => x.CustomerEmail)
        </div>


        @if (isAdmin)
    {
        <div class="form-group note-container">
            <label>
                Notes
                <span class="btn btn-default btn-sm glyphicon glyphicon-edit btn-edit-note" title="Click to add note"></span>
            </label>

            <textarea name="Description" rows="4" class="form-control hidden"></textarea>
            @Html.For(model).TextArea("ReadOnlyDescription", ViewHelper.ToNoteDisplay(model.Description),ViewHelper.GetHtmlAttributes(rows: 4, @readonly: true))
            @Html.For(model).ValidationMessageFor(x => x.Description)
        </div>
}

        <div class="form-group">
            <input type="submit" value="Save & Continue" id="btn-continue" class="btn btn-primary" />
        </div>
    </form>
    @if (showSecuredUpload)
    {
        Html.RenderAction("Files", "FileUploads", new { ownerId = model.WorkOrderId, ownerType = FileOwnerType.SecuredWorkOrder });

    }

    <script>
        $(app.workorders.initWorkOrderSettings);
    </script>
</div>

ImagePainting.Site.Web/Views/WorkOrders/ScheduleTasks.cshtml
 @model SiteViewModel<List<ScheduleWorkOrderTask>>
@{ 
    var model = Model.ViewModel;
    var selectedTasks = model.Where(x => x.Selected);
    var completedTasks = model.Where(x => x.Completed);
}
<div class="wo-step-screen" data-node="scheduleTasks">
    <h3>Schedule Tasks</h3>

    @using (Html.BeginForm("ScheduleTasks", "WorkOrders", FormMethod.Post, new { novalidate = "true", id = "scheduleForm"}))
    {
        @Html.AntiForgeryToken()
        @Html.For(model).Hidden("Id")
        for (int i = 0; i < selectedTasks.Count(); i++)
        {
            var task = selectedTasks.ElementAt(i);
            var taskDate = task.Date.HasValue ? task.Date.Value.ToString("yyyy-MM-dd") : string.Empty;
            var cantChangeSchedule = !(task.Permission?.CanChangeSchedule ?? true);

            <div class="row task-rows">
                <div class="col-md-4 form-group">
                    @Html.For(model).Hidden($"[{i}].TaskId", task.TaskId,ViewHelper.GetHtmlAttributes(@class: "item-task-id"))
                    <label class="check">
                        @Html.For(model).CheckBox($"[{i}].Selected", task.Selected,ViewHelper.GetHtmlAttributes(formControl: false, disabled: task.CantUnselect, @class: "item-task-selected"))
                        <span class="animated-checkbox"><i class="animated-checkbox-icon glyphicon glyphicon-ok"></i></span>
                        @Html.For(model).Hidden($"[{i}].TaskName", task.TaskName,ViewHelper.GetHtmlAttributes(@class: "item-task-name"))
                        @task.TaskName
                    </label>
                    @Html.For(model).Hidden($"[{i}].SchemaId", task.SchemaId,ViewHelper.GetHtmlAttributes(@class: "item-task-schema-id"))
                </div>
                <div class="col-md-4 form-group">
                    <div class="input-group">
                        <div class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></div>
                        @Html.For(model).TextBox($"[{i}].Date", taskDate,ViewHelper.GetHtmlAttributes(type: "date", disabled: cantChangeSchedule, @class: "item-task-date", dataValue: taskDate))
                    </div>
                </div>
                <div class="col-md-4 form-group">
                    <div class="input-group">
                        <div class="input-group-addon"><i class="glyphicon glyphicon-user"></i></div>
                        @Html.For(model).DropDownList($"[{i}].UserId", Model.ViewHelper.GetUsersOptions(task.UserId, false, true),ViewHelper.GetHtmlAttributes(disabled: cantChangeSchedule, @class: "item-task-user-id", dataValue: task.UserId))
                    </div>
                </div>
            </div>
        }
        <div class="row form-group">
            <div class="col-md-5">
                <a id="scheduleTaskLink">Schedule New Task</a>
                @Html.For(model).DropDownList("ScheduleNewTask", 
               Model.ViewHelper.ScheduleTaskListToTaskOptions(model.Where(x => !x.Permission.IsNull() && !x.Permission.CanCreateDuplicateTask).Select(x => x.SchemaId)),
              ViewHelper.GetHtmlAttributes(@class: "hidden"))
            </div>
        </div>

        <div class="row form-group">
            <br />
            <input type="button" value="Cancel" class="btn btn-default" />
            <input type="submit" value="Save & Continue" id="btn-continue" class="btn btn-primary" />
        </div>
    }

    <div class="row task-rows hidden" id="cloneable">
        <div class="col-md-4 form-group">
            @Html.For(model).Hidden("[0].TaskId", 0,ViewHelper.GetHtmlAttributes(@class: "item-task-id"))
            <label class="check">
                @Html.For(model).CheckBox("[0].Selected", true,ViewHelper.GetHtmlAttributes(formControl: false, @class: "item-task-selected"))
                <span class="animated-checkbox"><i class="animated-checkbox-icon glyphicon glyphicon-ok"></i></span>
            </label>
            @Html.For(model).Hidden("[0].SchemaId", 0,ViewHelper.GetHtmlAttributes(@class: "item-task-schema-id"))
        </div>
        <div class="col-md-4 form-group">
            <div class="input-group">
                <div class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></div>
                @Html.For(model).TextBox("[0].Date", null,ViewHelper.GetHtmlAttributes(type: "date", @class: "item-task-date", dataValue: null))
            </div>
        </div>
        <div class="col-md-4 form-group">
            <div class="input-group">
                <div class="input-group-addon"><i class="glyphicon glyphicon-user"></i></div>
                @Html.For(model).DropDownList("[0].UserId", Model.ViewHelper.GetUsersOptions(string.Empty, false, true),ViewHelper.GetHtmlAttributes(@class: "item-task-user-id", dataValue: string.Empty))
            </div>
        </div>
    </div>

    <script>
        $(app.workorders.initScheduleTasks(@Html.Raw(completedTasks.Select(x => x.TaskName).ToJson())));
    </script>
</div>